<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="TestAll" duration-ms="85" started-at="2016-06-27T22:05:40Z" finished-at="2016-06-27T22:05:40Z">
    <groups>
      <group name="scheduler">
        <method signature="TestScheduler.testScheduler1()[pri:0, instance:com.terra.qatest1.TestScheduler@176d53b2]" name="testScheduler1" class="com.terra.qatest1.TestScheduler"/>
        <method signature="TestScheduler.testScheduler2()[pri:0, instance:com.terra.qatest1.TestScheduler@176d53b2]" name="testScheduler2" class="com.terra.qatest1.TestScheduler"/>
      </group> <!-- scheduler -->
      <group name="db-nosql">
        <method signature="TestDatabase.testConnectMongoDB()[pri:0, instance:com.terra.qatest1.TestDatabase@2d2e5f00]" name="testConnectMongoDB" class="com.terra.qatest1.TestDatabase"/>
      </group> <!-- db-nosql -->
      <group name="db">
        <method signature="TestDatabase.testConnectOracle()[pri:0, instance:com.terra.qatest1.TestDatabase@2d2e5f00]" name="testConnectOracle" class="com.terra.qatest1.TestDatabase"/>
      </group> <!-- db -->
      <group name="iot">
        <method signature="TestIot.testScheduler1()[pri:0, instance:com.terra.qatest1.TestIot@157632c9]" name="testScheduler1" class="com.terra.qatest1.TestIot"/>
        <method signature="TestIot.testScheduler2()[pri:0, instance:com.terra.qatest1.TestIot@157632c9]" name="testScheduler2" class="com.terra.qatest1.TestIot"/>
      </group> <!-- iot -->
    </groups>
    <test name="scheduler" duration-ms="39" started-at="2016-06-27T22:05:40Z" finished-at="2016-06-27T22:05:40Z">
      <class name="com.terra.qatest1.TestScheduler">
        <test-method status="PASS" signature="testScheduler1()[pri:0, instance:com.terra.qatest1.TestScheduler@176d53b2]" name="testScheduler1" duration-ms="23" started-at="2016-06-27T15:05:40Z" finished-at="2016-06-27T15:05:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testScheduler1 -->
        <test-method status="FAIL" signature="testScheduler2()[pri:0, instance:com.terra.qatest1.TestScheduler@176d53b2]" name="testScheduler2" duration-ms="2" started-at="2016-06-27T15:05:40Z" finished-at="2016-06-27T15:05:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at org.testng.Assert.assertEquals(Assert.java:298)
	at com.terra.qatest1.TestScheduler.testScheduler2(TestScheduler.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testScheduler2 -->
      </class> <!-- com.terra.qatest1.TestScheduler -->
    </test> <!-- scheduler -->
    <test name="database" duration-ms="30" started-at="2016-06-27T22:05:40Z" finished-at="2016-06-27T22:05:40Z">
      <class name="com.terra.qatest1.TestDatabase">
        <test-method status="PASS" signature="testConnectMongoDB()[pri:0, instance:com.terra.qatest1.TestDatabase@2d2e5f00]" name="testConnectMongoDB" duration-ms="23" started-at="2016-06-27T15:05:40Z" finished-at="2016-06-27T15:05:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testConnectMongoDB -->
        <test-method status="PASS" signature="testConnectOracle()[pri:0, instance:com.terra.qatest1.TestDatabase@2d2e5f00]" name="testConnectOracle" duration-ms="1" started-at="2016-06-27T15:05:40Z" finished-at="2016-06-27T15:05:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testConnectOracle -->
      </class> <!-- com.terra.qatest1.TestDatabase -->
    </test> <!-- database -->
    <test name="iot" duration-ms="5" started-at="2016-06-27T22:05:40Z" finished-at="2016-06-27T22:05:40Z">
      <class name="com.terra.qatest1.TestIot">
        <test-method status="PASS" signature="testScheduler1()[pri:0, instance:com.terra.qatest1.TestIot@157632c9]" name="testScheduler1" duration-ms="1" started-at="2016-06-27T15:05:40Z" finished-at="2016-06-27T15:05:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testScheduler1 -->
        <test-method status="FAIL" signature="testScheduler2()[pri:0, instance:com.terra.qatest1.TestIot@157632c9]" name="testScheduler2" duration-ms="1" started-at="2016-06-27T15:05:40Z" finished-at="2016-06-27T15:05:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at org.testng.Assert.assertEquals(Assert.java:298)
	at com.terra.qatest1.TestIot.testScheduler2(TestIot.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testScheduler2 -->
      </class> <!-- com.terra.qatest1.TestIot -->
    </test> <!-- iot -->
  </suite> <!-- TestAll -->
</testng-results>
